### ISSUE TITLE
Just doesn't work :( 

### ISSUE THREAD

**Issue by domainregistrar** [hexonet/whmcs-ispapi-domainchecker#101] opened 2019-08-29 00:13 UTC
**Describe the bug**
Does not load correctly in Admin nor Front-end, completely non-functional.

**To Reproduce**
Go to /mydomainchecker.php - doesn't load filters/categories, shows red alert with "undefined undefined!"

**Expected behavior**
To work as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/42817204/63900815-c7584000-c9f9-11e9-9f6e-5669a83d2fdb.png)

![image](https://user-images.githubusercontent.com/42817204/63900837-dfc85a80-c9f9-11e9-84ff-2f3e2ea2db99.png)

**Context (please complete the following information):**
 - Device: Desktop
 - OS: MacOS
 - Browser Chrome 76.0.3809.100
 - WHMCS Version 7.8
 - PHP Version 7.2.21
 - ISPAPI Domainchecker Module Version v10.0.6

**Comment by domainregistrar** [comment] 2019-08-29 00:26
Also confirmed with PHP 7.3.8 & with incognito / cleared caches etc.

**Comment by papakai** [comment] 2019-08-29 08:33
Hi @domainregistrar 

At least we know v10.0.6 of our module to be working with WHMCS 7.7.x. If WHMCS 7.8 introduces changes that break our module, it is basically something they are doing wrong in their release strategy.

version x.y.z 
x stands for major release that comes with breaking changes
y stands for minor release that comes with new features / reviews, no breaking changes!
z stands for patch release -> bug fixes / patches, no breaking changes!

7.7.x to 7.8.y is a feature release upgrade and should not break anything, but it does.

So, back to your problem:
I have noticed yesterday evening that the backend part of domainchecker stopped working after upgrade, but it was already too late to dive into fixing. the frontend part still works on my test server.

I am already working for an fix for the backend part. which is from what I saw issued because WHMCS 7.8 drops JQuery UI in admin theme. I will come back to you with the frontend part after that directly.

**Comment by papakai** [comment] 2019-08-29 08:38
fyi: I think their release strategy won't improve, so I am bringing this up internally that we dive into testing beta and release candidates in future too, so that we at least have a chance to get issues resolved in advance as far as it is possible.

**Comment by papakai** [comment] 2019-08-29 08:53
@domainregistrar I've released a new major version 11.0.0 that fixes the admin area issue. I decided to release it as major release because we had to re-introduce JQuery-UI, but I am not 100% sure if this will still work with WHMCS 7.7.x. So we can easier distinguish compatibility imo.

**Comment by papakai** [comment] 2019-08-29 08:59
The frontend issue I am able to reproduce, but this is because of a non-working url-rewrite on my side and it looks like you have a similar issue on your side.
So maybe you don't have one of our url rewrite solutions rolled out (described in section 3 e of the [Usage Guide](https://github.com/hexonet/whmcs-ispapi-domainchecker/wiki/Usage-Guide#e-redirect-the-whmcs-domainchecker-file)) or you maybe have the same problems I am currently also faced with. Have you maybe also upgraded your apache2 to a new version? I am using 2.4.38 and I remember having it upgraded in the last days - now the url rewrite no longer works on my machine. Since hours I am trying to figure the reasons out for that.

**Comment by papakai** [comment] 2019-08-29 09:59
with 11.0.1 it works now also directly from mydomainchecker.php file in case no url rewrite solution is in use or not working for any reason. Let me know if that did not help - I will reopen that issue then.

**Closed** 2019-08-29 11:28 UTC

**Comment by papakai** [comment] 2019-08-29 14:58
11.0.3 targets an issue with incoming transfer request (customer clicks on Transfer instead of Search), this is now also corrected and did a lot of trouble in my instance. This was also working for us before WHMCS 7.8.

**Comment by domainregistrar** [comment] 2019-08-29 23:38
Can confirm no issues found so far with 11.0.3 - Many thanks for super quick fix guys! :D

**Comment by papakai** [comment] 2019-08-30 06:35
You're always welcome Dan :-)
